function cfg = getScenariosConfig()
%GETSCENARIOSCONFIG Restituisce la configurazione di tutti gli scenari.
%   Ogni elemento di cfg è una struct con campi:
%     - key   : chiave univoca per l'accesso (es. 'Partner')
%     - label : etichetta visualizzata nell'interfaccia
%     - restr : struct('dist',...,'time',...,'Dc',...) per fase restrittiva
%     - ord   : struct('dist',...,'time',...,'Dc',...) per fase ordinaria
%     - ord2m : struct('dist',...,'time',...,'Dc',...) variante ≥2 m (solo Colleghi)

    % placeholder “vuoto” per ord2m pro tutti tranne “Colleghi”
    empty2m = struct('dist',[],'time',[],'Dc',0);

    cfg = [ ...
        struct('key','Partner',   'label','Partner', ...
               'restr',struct('dist',[1.0],       'time',[2.0],       'Dc',3.0), ...
               'ord',  struct('dist',[0.3,1.0,2], 'time',[6,3.5,9.5], 'Dc',0), ...
               'ord2m', empty2m ), ...
        struct('key','Trasporto','label','Trasporto pubblico', ...
               'restr',struct('dist',[],          'time',[],          'Dc',0.3), ...
               'ord',  struct('dist',[0.3,1,999], 'time',[1,2,20.5],  'Dc',0), ...
               'ord2m', empty2m ), ...
        struct('key','Bambino02','label','Bambino <2 aa', ...
               'restr',struct('dist',[1.0,2.0],   'time',[1.5,2.0],   'Dc',1.0), ...
               'ord',  struct('dist',[0.1,0.3,1,2],'time',[1.5,4,6,12], 'Dc',0), ...
               'ord2m', empty2m ), ...
        struct('key','Bambino25','label','Bambino 2–5 aa', ...
               'restr',struct('dist',[1.0,2.0],   'time',[1.5,1.5],   'Dc',1.0), ...
               'ord',  struct('dist',[0.1,2.0,999],'time',[2,6,16],     'Dc',0), ...
               'ord2m', empty2m ), ...
        struct('key','Bambino511','label','Bambino 5–11 aa', ...
               'restr',struct('dist',[1.0],       'time',[2.5],       'Dc',1.0), ...
               'ord',  struct('dist',[0.5,1.0,2.0,999],'time',[2.5,3.0,6.0,12.0],'Dc',0), ...
               'ord2m', empty2m ), ...
        struct('key','Incinta','label','Donna incinta', ...
               'restr',struct('dist',[1.0],     'time',[2.0],     'Dc',1.0), ...
               'ord',  struct('dist',[1.0,999], 'time',[6,18],    'Dc',0), ...
               'ord2m', empty2m ), ...
        struct('key','Colleghi','label','Colleghi lavoro', ...
               'restr',struct('dist',[],     'time',[],       'Dc',0.3), ...
               'ord',  struct('dist',[1.0,999], 'time',[8,16]*0.9093,'Dc',0), ...
               'ord2m',struct('dist',[2.0,999], 'time',[8,16],    'Dc',0) ) ...
    ];
end
